//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sport_tovari_Belyaeva_3902.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tovar
    {
        public int idtovar { get; set; }
        public string artikul { get; set; }
        public string name { get; set; }
        public string edizm { get; set; }
        public Nullable<int> stoimost { get; set; }
        public Nullable<int> maxsk { get; set; }
        public string proizvoditel { get; set; }
        public Nullable<int> IDpostavchil { get; set; }
        public Nullable<int> IDkategorya { get; set; }
        public Nullable<int> DeistvSkidka { get; set; }
        public Nullable<int> kolvonaskl { get; set; }
        public string opisanie { get; set; }
        public string image { get; set; }
    
        public virtual kategorya kategorya { get; set; }
        public virtual Postavchik Postavchik { get; set; }
    }
}
