//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sport_tovari_Belyaeva_3902.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int iduser { get; set; }
        public Nullable<int> IDrole { get; set; }
        public string FIO { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual role role { get; set; }
    }
}
