//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sport_tovari_Belyaeva_3902.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class zakaz
    {
        public int idzakaz { get; set; }
        public Nullable<int> nomerz { get; set; }
        public string sostavz { get; set; }
        public Nullable<System.DateTime> dataz { get; set; }
        public Nullable<System.DateTime> datapost { get; set; }
        public Nullable<int> IDpunkt { get; set; }
        public string FIO { get; set; }
        public Nullable<int> kodpol { get; set; }
        public Nullable<int> IDstatus { get; set; }
    
        public virtual punkt punkt { get; set; }
        public virtual status status { get; set; }
    }
}
